# Generated by Django 2.0.6 on 2018-06-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_confirmation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='is_used',
        ),
    ]
