# Generated by Django 2.0.6 on 2018-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
